### ISSUE TITLE
support dart-sass

### ISSUE THREAD

**Issue by chriseppstein** [linkedin/eyeglass#173]
Once Dart-Sass implements the node-sass API this should be relatively straightforward.

https://github.com/sass/dart-sass/issues/12

**Comment by nex3** [comment]
Dart Sass now implements the Node Sass API! I'm happy to help out with a pull-request here, but I'm not sure what the design should look like. In particular, it would be really nice for Dart Sass users not to have to install Node Sass, but right now Eyeglass lists Node Sass as a dependency. What's the best way around that?

**Comment by chriseppstein** [comment]
This is fixed in `eyeglass@3.0.0`!
