### ISSUE TITLE
Allow defaulting the value of verbose mode via environment variable

### ISSUE THREAD

**Issue by chriseppstein** [linkedin/eyeglass#230]
Maybe trigger it off of `DEBUG="eyeglass:results"` or some other var?

**Comment by rwjblue** [comment]
Generally speaking the [debug](https://www.npmjs.com/package/debug) package or [heimdall-logger](https://www.npmjs.com/package/heimdalljs-logger) "own" `process.env.DEBUG`. Any reason not to use those packages for this debug logging directly?

**Comment by chriseppstein** [comment]
@rwjblue I use the debug package for a lot of logging in eyeglass. The reason I'm using `console.log` directly is that I envisioned the output as more of a first class UI and not actually debugging information.

I'm not opposed to using a logger for this. It would also be good to integrate with `ember-cli`'s `ui` logger when running in that context.

This issue is pretty low priority for me so I was looking to do the simplest thing for now, and checking if an env variable was set is a quick and dirty solution.

I actually have a patch for this already. Is your suggestion that I not drive this off of the `DEBUG` setting? I liked that `DEBUG="eyeglass:*,broccoli-eyeglass:*"` would enable all my debug logging and this UI as well.

**Comment by gabrielcsapo** [comment]
That would be great IMO, then we wouldn't have to introduce a new mechanism to control debugging

**Comment by chriseppstein** [comment]
Fixed by fd18a12552a66893d4ac71e2ed3b3cd904f82b06.
