### ISSUE TITLE
Eyeglass failing @imports

### ISSUE THREAD

**Issue by heyrichardshi** [linkedin/eyeglass#238]
**Package**
This issue is related to the following monorepo package(s):
- [x] eyeglass 
- [ ] broccoli-eyeglass
- [ ] ember-cli-eyeglass

**Description**
A clear and concise description of the issue.
`@import`ing Bourbon and Neat (both eyeglass-aware modules) fails in simple setup.

**To Reproduce**
1. `npm i node-sass eyeglass bourbon --save-dev`
2. `@import "bourbon"`
3. Compiling gives error: `File to import not found or unreadable: bourbon.`

**Expected behavior**
Successful `@import`

**Screenshots/Code Examples/Terminal Commands**
My `package.json`:
```
{
  "name": "ising-model",
  "version": "1.0.0",
  "description": "ising model on the web",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/heyrichardshi/ising-model.git"
  },
  "author": "",
  "license": "ISC",
  "bugs": {
    "url": "https://github.com/heyrichardshi/ising-model/issues"
  },
  "homepage": "https://github.com/heyrichardshi/ising-model#readme",
  "devDependencies": {
    "bourbon": "^5.1.0",
    "bourbon-neat": "^3.0.1",
    "eyeglass": "^2.4.1",
    "normalize-scss": "^7.0.1"
  },
  "dependencies": {}
}
```

**Environment:**
 - OS: Unix or Windows? Unix
 - Node version: 12.3.0
 - Related Software and Version(s): sass-autocompile for Atom

**Comment by chriseppstein** [comment]
It doesn't seem like `sass-autocompile` is eyeglass aware, so this would be expected. At a minimum that project would need to expose a way to provide a file path to javascript module that exports a function that receives options and returns new options that can be passed through to node sass. this function would need to be invoked for each compile.
